-- =====================================================================
--  Sunrise Dental Clinic - V3 seed data
--
--      mysql -u root -p < database/V3__seed.sql
--
--  PASSWORDS
--  password_hash holds PBKDF2-HMAC-SHA256 at 210,000 iterations with a
--  per-user 16-byte random salt, generated by
--      java -cp target/classes lk.icbt.dentalclinic.security.PasswordHasher
--  No plaintext and no bare digest is ever stored. The demo passwords
--  below are documented here only because this is coursework with a
--  throwaway database; a real deployment would force a change on first
--  login.
--
--      admin        Admin@123      ADMIN
--      dr.perera    Dentist@123    DENTIST
--      dr.silva     Dentist@456    DENTIST
--      kasun.f      Patient@123    PATIENT
--      nadeesha.w   Patient@456    PATIENT
-- =====================================================================

USE sunrise_clinic;


-- ---------------------------------------------------------------------
-- Roles. RECEPTIONIST from the reference schema is deliberately folded
-- into ADMIN - it had no behaviour of its own (assumption A3).
-- ---------------------------------------------------------------------
INSERT INTO roles (code, description) VALUES
    ('ADMIN',   'Clinic administrator - full access to all records and reports'),
    ('DENTIST', 'Dentist - own schedule and assigned patients'),
    ('PATIENT', 'Patient - self-service booking and own records');


-- ---------------------------------------------------------------------
-- Clinic settings, read by fn_appointment_total and the booking
-- validator instead of being hard-coded in Java.
--
-- tax.rate is 0 because dental healthcare services are VAT-exempt in
-- Sri Lanka. The setting and the bill column exist so a rate can be
-- applied without a schema change if that ever alters.
-- ---------------------------------------------------------------------
INSERT INTO clinic_settings (setting_key, setting_value, description) VALUES
    ('consultation.fee',  '2500.00', 'Standard consultation fee added to every bill (LKR)'),
    ('tax.rate',          '0.0000',  'Tax applied to the discounted subtotal (0 = exempt)'),
    ('discount.max.pct',  '25.00',   'Maximum discount as a percentage of the subtotal'),
    ('clinic.open',       '08:00',   'Earliest bookable appointment time'),
    ('clinic.close',      '20:00',   'Latest bookable appointment time'),
    ('slot.minutes',      '30',      'Appointment slots must fall on this boundary'),
    ('clinic.name',       'Sunrise Dental Clinic', 'Name printed on receipts'),
    ('clinic.address',    '221 Galle Road, Colombo 03', 'Address printed on receipts');


-- ---------------------------------------------------------------------
-- Users. Hashes below are real PBKDF2 output - note that the two
-- dentists have different salts, so identical passwords would still
-- produce different hashes.
-- ---------------------------------------------------------------------
INSERT INTO users (username, password_hash, full_name, email, role_id, active) VALUES
    ('admin',
     'pbkdf2-sha256$210000$U6s/Xe4C0h95yYJWgWySog$dxcnEnvMBAPYVEpweedKn7z+6970frtYTxWwWbRnuFI',
     'System Administrator', 'admin@sunrisedental.lk',
     (SELECT role_id FROM roles WHERE code = 'ADMIN'), TRUE),

    ('dr.perera',
     'pbkdf2-sha256$210000$8GFpx7U2cLdfn0Y5vIW9Uw$nHUL8+UZa+X03OtYP0wX+8P+RaxwVn+5znooGC2trL4',
     'Dr. Nimal Perera', 'nimal.perera@sunrisedental.lk',
     (SELECT role_id FROM roles WHERE code = 'DENTIST'), TRUE),

    ('dr.silva',
     'pbkdf2-sha256$210000$r1ex+ZfKOjr7b+sER4kY7Q$9K3cLM/GYXeFPeYtvBsARrwZ2LWDULmW/fczFlwSq1Y',
     'Dr. Anjali Silva', 'anjali.silva@sunrisedental.lk',
     (SELECT role_id FROM roles WHERE code = 'DENTIST'), TRUE),

    ('kasun.f',
     'pbkdf2-sha256$210000$G3jWsvfaOKbWhCmhbF3Mdw$uQpo7UyHp1pYtmca4ENVP21crwGLVeC3Ds0WimVhAPM',
     'Kasun Fernando', 'kasun.fernando@example.lk',
     (SELECT role_id FROM roles WHERE code = 'PATIENT'), TRUE),

    ('nadeesha.w',
     'pbkdf2-sha256$210000$Px5iwOC3Zjm592lL7V1tlA$IRnGmbbsAhGVh7jMYCRtTGgHhFJQNTCAfSeG6YBkRH0',
     'Nadeesha Wickramasinghe', 'nadeesha.w@example.lk',
     (SELECT role_id FROM roles WHERE code = 'PATIENT'), TRUE);


-- ---------------------------------------------------------------------
-- Dentists, each linked to a login. session_start / session_end differ
-- so the booking validator has something real to reject against.
-- ---------------------------------------------------------------------
INSERT INTO dentists (user_id, full_name, specialization, phone, email,
                      session_start, session_end, active) VALUES
    ((SELECT user_id FROM users WHERE username = 'dr.perera'),
     'Dr. Nimal Perera', 'General Dentistry', '0771234567',
     'nimal.perera@sunrisedental.lk', '08:00:00', '16:00:00', TRUE),

    ((SELECT user_id FROM users WHERE username = 'dr.silva'),
     'Dr. Anjali Silva', 'Orthodontics', '0772345678',
     'anjali.silva@sunrisedental.lk', '12:00:00', '20:00:00', TRUE);


-- ---------------------------------------------------------------------
-- Patients. PAT-000003 has no user_id: registered at the desk by an
-- administrator, with no self-service login (assumption A2).
-- ---------------------------------------------------------------------
INSERT INTO patients (patient_no, user_id, full_name, address, contact_number,
                      email, date_of_birth) VALUES
    ('PAT-000001',
     (SELECT user_id FROM users WHERE username = 'kasun.f'),
     'Kasun Fernando', '14/3 Temple Road, Nugegoda', '0761112223',
     'kasun.fernando@example.lk', '1994-03-18'),

    ('PAT-000002',
     (SELECT user_id FROM users WHERE username = 'nadeesha.w'),
     'Nadeesha Wickramasinghe', '88 Lake Drive, Rajagiriya', '0762223334',
     'nadeesha.w@example.lk', '1988-11-02'),

    ('PAT-000003', NULL,
     'Sunil Jayawardena', '5 Station Road, Mount Lavinia', '0763334445',
     NULL, '1971-07-25');


-- ---------------------------------------------------------------------
-- Treatments. `family` is what PricingStrategyFactory resolves on in M4,
-- so adding a treatment to an existing family needs no new Java code.
-- ---------------------------------------------------------------------
INSERT INTO treatments (code, name, family, description, base_cost, duration_minutes) VALUES
    ('CONSULT', 'Consultation',          'CONSULTATION', 'General dental examination and advice',        0.00,    20),
    ('CLEAN',   'Scaling and Polishing', 'CLEANING',     'Removal of plaque and calculus, polish',    5000.00,    30),
    ('FILL',    'Composite Filling',     'FILLING',      'Tooth-coloured restoration, single surface', 7500.00,    45),
    ('EXTRACT', 'Simple Extraction',     'EXTRACTION',   'Non-surgical removal of a single tooth',    10000.00,    30),
    ('RCT',     'Root Canal Treatment',  'ROOT_CANAL',   'Endodontic treatment, single canal',        25000.00,    90),
    ('CROWN',   'Porcelain Crown',       'PROSTHETIC',   'Full-coverage porcelain crown',             35000.00,    60),
    ('WHITEN',  'Teeth Whitening',       'COSMETIC',     'In-clinic bleaching, single session',       18000.00,    60);


-- ---------------------------------------------------------------------
-- Help topics - brief requirement 5.
-- ---------------------------------------------------------------------
INSERT INTO help_topics (title, body, audience, display_order) VALUES
    ('Signing in',
     'Enter the username and password issued to you and choose Sign in. After five failed attempts the account locks for 15 minutes. Contact an administrator if you have forgotten your password - staff cannot reset it themselves.',
     'ALL', 10),

    ('Registering a new appointment',
     '1. Choose Appointments, then New appointment.\n2. Enter the patient name, address and contact number. An existing patient can be found by contact number instead.\n3. Choose the dentist, the treatment, and the date and time.\n4. Choose Save. The system allocates an appointment number in the form APT-2026-0001 and shows it on screen - write it on the patient card.\n\nIf the chosen slot is already taken the system refuses it and lists the next free times for that dentist.',
     'STAFF', 20),

    ('Finding an appointment',
     'Choose Appointments, then Search, and enter the appointment number. Capitalisation does not matter. The result shows the full patient record, the treatment, the dentist and any bill already issued.',
     'STAFF', 30),

    ('Producing a bill and receipt',
     'Open the appointment and choose Generate bill. The total is the consultation fee plus the treatment charge, less any discount. A discount may not exceed 25 per cent of the subtotal. Choose Print receipt for a printer-ready copy.',
     'STAFF', 40),

    ('Booking your own appointment',
     'Sign in, choose Book appointment, then pick a treatment, a dentist and a time from the free slots offered. You can reschedule or cancel your own appointments up to 24 hours beforehand from My appointments.',
     'PATIENT', 50),

    ('Closing the system',
     'Choose Sign out from the menu at the top right. This ends your session immediately. Closing the browser tab without signing out leaves the session to expire on its own after 30 minutes of inactivity.',
     'ALL', 60);


-- ---------------------------------------------------------------------
-- Sample appointments, so the reports and the dentist workload view
-- return real numbers on a fresh install.
--
-- Inserting these also exercises trg_appointment_audit_ins: the
-- verification block at the end of this file asserts that audit_log has
-- one row per appointment.
-- ---------------------------------------------------------------------
SET @admin_id = (SELECT user_id FROM users WHERE username = 'admin');
SET @yr       = YEAR(CURDATE());

INSERT INTO appointments (appointment_no, patient_id, dentist_id, treatment_id,
                          appointment_date, appointment_time, status, notes, created_by) VALUES
    (CONCAT('APT-', @yr, '-0001'),
     (SELECT patient_id   FROM patients   WHERE patient_no = 'PAT-000001'),
     (SELECT dentist_id   FROM dentists   WHERE full_name  = 'Dr. Nimal Perera'),
     (SELECT treatment_id FROM treatments WHERE code       = 'CLEAN'),
     CURDATE() - INTERVAL 7 DAY, '09:00:00', 'COMPLETED', 'Routine six-month clean', @admin_id),

    (CONCAT('APT-', @yr, '-0002'),
     (SELECT patient_id   FROM patients   WHERE patient_no = 'PAT-000002'),
     (SELECT dentist_id   FROM dentists   WHERE full_name  = 'Dr. Anjali Silva'),
     (SELECT treatment_id FROM treatments WHERE code       = 'FILL'),
     CURDATE() - INTERVAL 3 DAY, '14:30:00', 'COMPLETED', 'Upper left first molar', @admin_id),

    (CONCAT('APT-', @yr, '-0003'),
     (SELECT patient_id   FROM patients   WHERE patient_no = 'PAT-000003'),
     (SELECT dentist_id   FROM dentists   WHERE full_name  = 'Dr. Nimal Perera'),
     (SELECT treatment_id FROM treatments WHERE code       = 'EXTRACT'),
     CURDATE() - INTERVAL 1 DAY, '11:00:00', 'CANCELLED', 'Patient rescheduled by telephone', @admin_id),

    (CONCAT('APT-', @yr, '-0004'),
     (SELECT patient_id   FROM patients   WHERE patient_no = 'PAT-000001'),
     (SELECT dentist_id   FROM dentists   WHERE full_name  = 'Dr. Anjali Silva'),
     (SELECT treatment_id FROM treatments WHERE code       = 'RCT'),
     CURDATE() + INTERVAL 2 DAY, '15:00:00', 'BOOKED', 'First of two visits', @admin_id);

-- The four numbers above were assigned by hand, so the sequence must be
-- advanced to match or sp_next_appointment_no would hand out a duplicate.
INSERT INTO appointment_sequence (seq_year, last_number)
VALUES (@yr, 4)
ON DUPLICATE KEY UPDATE last_number = GREATEST(last_number, 4);


-- ---------------------------------------------------------------------
-- One issued bill for the completed cleaning, so the revenue report has
-- data. total_amount is deliberately left at its default: the trigger
-- trg_bill_before_insert computes it.
-- ---------------------------------------------------------------------
INSERT INTO bills (bill_no, appointment_id, consultation_fee, treatment_charge,
                   discount_amount, tax_amount, status, issued_by) VALUES
    (CONCAT('BIL-', @yr, '-0001'),
     (SELECT appointment_id FROM appointments WHERE appointment_no = CONCAT('APT-', @yr, '-0001')),
     2500.00, 5000.00, 0.00, 0.00, 'PAID', @admin_id);

INSERT INTO bill_line_items (bill_id, description, quantity, unit_price, line_total) VALUES
    ((SELECT bill_id FROM bills WHERE bill_no = CONCAT('BIL-', @yr, '-0001')),
     'Consultation', 1, 2500.00, 2500.00),
    ((SELECT bill_id FROM bills WHERE bill_no = CONCAT('BIL-', @yr, '-0001')),
     'Scaling and Polishing', 1, 5000.00, 5000.00);

UPDATE bills SET paid_at = NOW() WHERE bill_no = CONCAT('BIL-', @yr, '-0001');


INSERT INTO schema_version (version, description)
VALUES ('V3', 'Seed data: 3 roles, 8 settings, 5 users, 2 dentists, 3 patients, 7 treatments');


-- ---------------------------------------------------------------------
-- Verification. Every line below should report OK.
-- ---------------------------------------------------------------------
SELECT 'roles'         AS entity, COUNT(*) AS rows_seeded, IF(COUNT(*) = 3, 'OK', 'FAIL') AS result FROM roles
UNION ALL SELECT 'clinic_settings', COUNT(*), IF(COUNT(*) = 8, 'OK', 'FAIL') FROM clinic_settings
UNION ALL SELECT 'users',           COUNT(*), IF(COUNT(*) = 5, 'OK', 'FAIL') FROM users
UNION ALL SELECT 'dentists',        COUNT(*), IF(COUNT(*) = 2, 'OK', 'FAIL') FROM dentists
UNION ALL SELECT 'patients',        COUNT(*), IF(COUNT(*) = 3, 'OK', 'FAIL') FROM patients
UNION ALL SELECT 'treatments',      COUNT(*), IF(COUNT(*) = 7, 'OK', 'FAIL') FROM treatments
UNION ALL SELECT 'help_topics',     COUNT(*), IF(COUNT(*) = 6, 'OK', 'FAIL') FROM help_topics
UNION ALL SELECT 'appointments',    COUNT(*), IF(COUNT(*) = 4, 'OK', 'FAIL') FROM appointments
UNION ALL SELECT 'bills',           COUNT(*), IF(COUNT(*) = 1, 'OK', 'FAIL') FROM bills
UNION ALL SELECT 'bill_line_items', COUNT(*), IF(COUNT(*) = 2, 'OK', 'FAIL') FROM bill_line_items
-- Written entirely by trg_appointment_audit_ins - proof the trigger fired.
UNION ALL SELECT 'audit_log (trigger)', COUNT(*), IF(COUNT(*) = 4, 'OK', 'FAIL') FROM audit_log;

-- Proof that trg_bill_before_insert computed the total: 2500 + 5000 - 0 + 0.
SELECT bill_no, consultation_fee, treatment_charge, total_amount,
       IF(total_amount = 7500.00, 'OK - trigger computed the total', 'FAIL') AS result
FROM bills;
